name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_image_name_frontend: tradewcs/frontend-internship-proj
          TF_VAR_image_name_gradle: tradewcs/gradle-intrernship-proj
          TF_VAR_image_tag: latest
        run: terraform apply
